name: Binder

on:
  create:
  push:
  workflow_dispatch:

jobs:
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        id: cancel_prev
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check
        uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":"this was awesome"}
      - name: Start Badge
        uses: RubbaBoy/BYOB@v1.1.0
        with:
          NAME: time
          LABEL: 'Binder'
          STATUS: 'Building'
          COLOR: '00AAAA'
          BRANCH: 'main'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: cache binder build on mybinder.org
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: v1 # This builds the container on mybinder.org with the branch that was pushed on.
      - name: End Badge
        uses: RubbaBoy/BYOB@v1.1.0
        with:
          NAME: time
          LABEL: 'Binder'
          STATUS: 'Built'
          COLOR: '005555'
          BRANCH: 'main'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
